### ISSUE TITLE
wont compile in freebsd

### ISSUE THREAD

**Issue by parlar** [clarkwang/passh#1] opened 2018-04-04 10:36 UTC
Hi, I had problems with sshpass in freebsd, so I thought i'd give passh a try. 

I need to rsync data from a nas to a freebsd machine. Use of ssh keys is disabled, as a lot of other stuff as well. (Avoid Seagate if you're buying a nas.)

However, I get an error when trying to compile.
```
$ make
cc -O2 -pipe  passh.c  -o passh
passh.c:805:49: warning: implicit conversion from 'int' to 'char' changes value from 255 to -1 [-Wconstant-conversion]
                            cache[ncache + i] = 255;
                                              ~ ^~~
passh.c:963:20: error: use of undeclared identifier 'SIGWINCH'
        sig_handle(SIGWINCH, sig_winch);
                   ^
1 warning and 1 error generated.
*** Error code 1
```

**Comment by clarkwang** [comment] 2018-04-04 15:53
I don't have a FreeBSD system for testing. Could you try removing the following lines and see if it compiles?

    #ifndef __APPLE__
    #define _XOPEN_SOURCE 600 /* for posix_openpt() */
    #endif

**Comment by clarkwang** [comment] 2018-04-04 16:35
Managed to find a FreeBSD VM and did some testing. The compile error is caused by `#define _XOPEN_SOURCE 600`. Fixed by not defining it on FreeBSD. Please pull and try again.

**Comment by parlar** [comment] 2018-04-05 10:53
Hi again,

Sorry about the slow response. Now now works!

Thanks,

Pär

**Closed** 2018-04-05 11:57 UTC
